apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - lovenotes.yaml
  - secret-lovenotes-admin-auth.yaml
  - lovenotes-basic-auth-middleware.yaml
  - image-policy.yaml
  - image-repository.yaml
  - image-update-automation.yaml
