apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-teslamate-ecryption-key.yaml
  - secret-teslamate-admin-auth.yaml
  - secret-grafana-admin-auth.yaml
  - secret-postgresql-db-auth.yaml
  - secret-cnpg-user-teslamate.yaml
  - secret-s3-credentials.yaml
  - teslamate-repository.yaml
  - teslamate-basic-auth-middleware.yaml
  - teslamate-release.yaml
  - teslamate-flux-alert.yaml
  - postgresql-cluster.yaml
