---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-auth-for-teslamate
  namespace: postgresql
spec:
  encryptedData:
    values.yaml: AgCIs+d5yC7APnacxqiD1r25Hw8No/Y2k7CqFAVIObGmn5Jjk78AsaWoWt+OwV9vYgz1NScyoZVFDlA1qpXgTu2AqV66zq8z1nxgRngX9MI74SQnEkg0SnWIrbCfJ6hTxw2E652/cS821wub5M+b78RfreD3ufm4MetmgDJjRYoKxXjrrcn6XCP1Wm0bjY4mMY4iQtDM5T0Cwcs2hu/Qqu6YxMpU4jKPfSdxV8EtDJhrvrcrp53eaTJUaJEEtzXf7bs5gJIhst3TQhIzYVCcdLu1OBsUB8BpW+bn+rIMzO424CKAtqNHOSAHV183JRE6F+UUJn89ljY1fhQx1vBej//pA7+THOJsdxNIQ46e9LUSQHwNT3AXof4oJ1aY3U/IgFlk1JXQWzQG1a2+w67mqqOhnjlSw2W6+7Xp5uFy7gt0/K7NX+J7fys9Wr/XRL7hpDkv1gFFZpnq6ie0jG6nSK5fVQQTmshFzh9j2w45IXCgego3ynCUSjfEsXzl4MLD3h/9jxJPo2+0b4VM/b11wZbKzXGxiIAZKUntuLpOCjGvauUTgl5/AYgtWRyCl3O+KMm3t5q3wD1a4iGRXoieBtAFE0g3MqkMPGkzuhxIVZtQ4M8nFZx9dSSjzngIQIIl0IfnHX4kZ1UFYW9ARiJWsLBgN32in/ZG0n/5OKPkLKJWLABv+ueC/i8wrozXF2hjSErxDqByP3pVsQMKkdRNFIC2PqdSuFlMJ4eQz1sqRTUxWjBo9Gw9hLTljHrKZalXDD5X75wE3V0y4GTTTn7f2BtLuCLz7V8GHw8z
  template:
    metadata:
      name: db-auth-for-teslamate
      namespace: postgresql
