---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-auth-for-teslamate
  namespace: postgresql
spec:
  encryptedData:
    values.yaml: AgBar5D7oxlhd+rSac2FjR542ryIRInAgNTIcaYKteUbpOM21OPyFJfqBsHyjUDSEH5DBH6q5I3zBLpmIZfK/kQYbFidHQi/etzPLRS9XZ4CzKLCFHqSlpJ8f1E08KtKDtfigN0W7sibC87eBhKJ78NG+LOVs+IbcMST+oPlTbwVinL0c5630G1zrycIbJlSf3sYKM9qu7KxdRmX9FniuaNjLDvilQIl7iM46bkdYYUwjGx+BhhmJi3ff75UlmVGDv05HKVEkzlQRiqOxOkNW3CBwHhYU9Zv9Q+bB4+38xGKkVrnc11QPgD88+Oh2nkYpjv2SY1pOr/dRdGOOiXMzmauNvcgKeys+A8hKRcZZvi4zGfp//xScWe2XgymAQMXKowA40bF4+LEqwknNoBR9z22B1gL+1N8QFXCL4YC5qX+8+W2TdRh5/x4gzl6l2VoCKs14Ws4/MqvSjX/jyFryW2BwvRhGEEFaA72Mo8zTDAPz21zZZbwnrd72DiWJK3FNt9G2KHz6JF0ttYFaW0PDzOeD2zg6/Ku3mwvVAlQLs8GIBNTqdyZVNR3cyCOBYJ7V7hAZ3wUuMOVUWL0TqYfZqry5PmWIYZKcLRkqW7rk8clR8aUxUZG6yorqe8qKMcdMCuJwywT4sOldahiusHJ+aVnDLABR1HNRT6baY4fvvuT/4VP6l9nfvifoE8R549p5q/5ly5S/SuSecgHqjM0BYnm+ZfgvYBOD1m5SL57mdTuGRyW0eM8n6FkcZ2g1icx9RIP79EXXE3N9Z1QOZfvosfHJzZIL7t8wtXW
  template:
    metadata:
      name: db-auth-for-teslamate
      namespace: postgresql
